
services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  
#   backend:
#     build: 
#       context: .
#       dockerfile: backend/Dockerfile
#     volumes:
#       - ./backend:/app/backend
#     environment:
#       - DATABASE_URL=${DATABASE_URL}
#     env_file:
#       - .env
#     ports:
#       - "8000:8000"
#     depends_on:
#       - database
#     networks:
#       - mynetwork
      
#   frontend:
#     build: 
#       context: .
#       dockerfile: frontend/Dockerfile
#     volumes:
#       - ./frontend:/app/frontend
#     ports:
#       - "8501:8501"
#     networks:
#       - mynetwork
  
# networks:
#   mynetwork:

volumes:
  local_pgdata:
  pgadmin-data: