"""properties table

Revision ID: d369125a327d
Revises: 
Create Date: 2024-08-28 19:01:27.088784

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd369125a327d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('number_bedrooms', sa.Enum('t0', 't1', 't2', 't3', 't4', 't5', 't6', 't6_plus', name='numbedrooms'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')

    conn = op.get_bind()
    if conn.dialect.name == 'postgresql':
        op.execute("DROP TYPE numbedrooms")
    # ### end Alembic commands ###
